### ISSUE TITLE
how do I update to new version

### ISSUE THREAD

**Issue by mehargags** [abbat/ydcmd#6]
Sorry for the stupid question, but I want to be absolutely sure before I fiddle with my production servers.
Can you please write exact steps

I'm on Debian 7

1. how to check the Version installed
2. how to update/upgrade your pkg
3. what services to restart (if any)

**Comment by abbat** [comment]
If you use package from [repository](http://software.opensuse.org/download.html?project=home:antonbatenev:ydcmd&package=ydcmd)

1)
```
# apt-cache policy ydcmd
ydcmd:
  Installed: 1.9
  Candidate: 1.9
```

2)
```
# apt-get update
# apt-get install ydcmd
```

3) None services to restart
